---
easy_BIO:
  BATCH_SIZE: 32
  N_SAMPLES: 50
  MODEL_NAME: "seiya/oubiobert-base-uncased"
  MODEL_ALIAS: "crossencoder"
  LOGGER_NAME: "crossencoder"
  CHECKPOINT: "best-checkpoint-v4.ckpt"
  GPUS: [0]
  MODE: "predict_w_labels"
  FIELDS: [
      'conditions',
      'brief_title',
      'official_title',
      'brief_summary',
      'detailed_description'
  ]
  QUERY_REPR: "description"
  RELEVANT_LABELS: [1, 2]
  PATH_2_RUN: "../../reports/DoSSIER_2"
  PATH_2_QRELS: "../../data/raw/2022_qrels_Judgment-of-0-is-non-relevant-2-is-excluded-and-2-is-eligible.txt"
  PATH_2_TRIALS: "../../data/processed/trials_parsed.jsonl"

DoSSIER_5_easy:
  BATCH_SIZE: 256
  N_SAMPLES: 50
  MODEL_NAME: seiya/oubiobert-base-uncased
  MODEL_ALIAS: "BIO_crossencoder"
  LOGGER_NAME: "BIO_crossencoder"
  CHECKPOINT: "best-checkpoint.ckpt"
  GPUS: [0]
  MODE: "predict_w_labels"
  FIELDS: [
    'conditions',
    'brief_title',
    'official_title',
    'brief_summary',
    'detailed_description'
  ]
  QUERY_REPR: "description"
  RELEVANT_LABELS: [1, 2]
  PATH_2_RUN: "../../reports/DoSSIER_2"
  PATH_2_QRELS: "../../data/raw/2022_qrels_Judgment-of-0-is-non-relevant-2-is-excluded-and-2-is-eligible.txt"
  PATH_2_TRIALS: "../../data/processed/trials_parsed.jsonl"
  VERSION: 2022

DoSSIER_5_difficult:
  BATCH_SIZE: 256
  N_SAMPLES: 100
  MODEL_NAME: seiya/oubiobert-base-uncased
  MODEL_ALIAS: "BIO_crossencoder"
  LOGGER_NAME: "BIO_crossencoder"
  CHECKPOINT: "best-checkpoint-v1.ckpt"
  GPUS: [ 0 ]
  MODE: "predict_w_labels"
  FIELDS: [
    'criteria',
  ]
  QUERY_REPR: "description"
  RELEVANT_LABELS: [ 1, 2 ]
  PATH_2_RUN: "../../reports/DoSSIER_5_easy"
  PATH_2_QRELS: "../../data/raw/2022_qrels_Judgment-of-0-is-non-relevant-2-is-excluded-and-2-is-eligible.txt"
  PATH_2_TRIALS: "../../data/processed/trials_parsed.jsonl"
  VERSION: 2022

DoSSIER_mixed:
  BATCH_SIZE: 256
  N_SAMPLES: 50
  MODEL_NAME: "bert-base-uncased"
  MODEL_ALIAS: "crossencoder"
  LOGGER_NAME: "crossencoder"
  CHECKPOINT: "best-checkpoint-v6.ckpt"
  GPUS: [ 0 ]
  MODE: "predict_w_labels"
  FIELDS: [
    'criteria',
  ]
  QUERY_REPR: "description"
  RELEVANT_LABELS: [ 1, 2 ]
  PATH_2_RUN: "../../reports/easy_BIO"
  PATH_2_QRELS: "../../data/raw/2022_qrels_Judgment-of-0-is-non-relevant-2-is-excluded-and-2-is-eligible.txt"
  PATH_2_TRIALS: "../../data/processed/trials_parsed.jsonl"

only_difficult:
  BATCH_SIZE: 256
  N_SAMPLES: 50
  MODEL_NAME: "bert-base-uncased"
  MODEL_ALIAS: "crossencoder"
  LOGGER_NAME: "crossencoder"
  CHECKPOINT: "best-checkpoint-v5.ckpt"
  GPUS: [ 0 ]
  MODE: "predict_w_labels"
  FIELDS: [
    'criteria',
  ]
  QUERY_REPR: "description"
  RELEVANT_LABELS: [ 2 ]
  PATH_2_RUN: "../../reports/DoSSIER_2"
  PATH_2_QRELS: "../../data/raw/2022_qrels_Judgment-of-0-is-non-relevant-2-is-excluded-and-2-is-eligible.txt"
  PATH_2_TRIALS: "../../data/processed/trials_parsed.jsonl"
