---
easy:
  BATCH_SIZE: 2
  N_SAMPLES: 4
  MODEL_NAME: "bert-base-uncased"
  MODEL_ALIAS: "crossencoder"
  LOGGER_NAME: "crossencoder"
  CHECKPOINT: "best-checkpoint-v1.ckpt"
  GPUS: null
  MODE: "predict_w_labels"
  FIELDS: [
      'conditions',
      'brief_title',
      'official_title',
      'brief_summary',
      'detailed_description'
  ]
  QUERY_REPR: "description"
  RELEVANT_LABELS: [1, 2]
  PATH_2_RUN: "../../reports/DoSSIER_1.txt"
  PATH_2_QRELS: "../../data/external/qrels2022.txt"
