---
curriculum_learning:
  BATCH_SIZE: 2
  N_SAMPLES: 4
  MODEL_NAME: "bert-base-uncased"
  MODEL_ALIAS: "crossencoder"
  LOGGER_NAME: "crossencoder"
  CHECKPOINT: "best-checkpoint-v1.ckpt"
  GPUS: null
  MODE: "predict_w_labels"
  FIELDS: [
      'conditions',
      'brief_title',
      'official_title',
      'brief_summary',
      'detailed_description'
  ]
  QUERY_REPR: "description"
  PATH_2_RUN: "../../reports/DoSSIER_1.txt"
  PATH_2_QRELS: "../../data/raw/qrels_Judgment-of-0-is-non-relevant-1-is-excluded-and-2-is-eligible.txt"
