---
curriculum_learning:
  SEED : 42
  TRAIN_BATCH_SIZE : 16
  EVAL_BATCH_SIZE: 32
  N_TRAIN_SAMPLES: 1024
  N_VAL_SAMPLES: 20
  N_TEST_SAMPLES: 20
  MODEL_NAME: "bert-base-uncased"
  WARMUP_STEPS: 0
  MODEL_ALIAS: crossencoder
  LOGGER_NAME: "crossencoder"
  TRACK_METRIC: P@10
  PATIENCE: 5
  N_EPOCHS: 10
  ACCUM_ITER : null
  EVAL_EVERY_N_EPOCH : 1
  GPUS: null


